#pragma config(Motor,  port2,           leftM,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightM,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armM,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           servM,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Ethan Davenport
// Testbed program for BEST robotics
// Version 1.1.0
// Build 0003
// 9/4/2018

#include "MotorRamping 0007.h"

task main()
{

	SmoothMotor left;
	SmoothMotor right;
	SmoothMotor arm;
	SmoothMotor serv;
	initSMotor(left, 50, leftM);
	initSMotor(right, 50, rightM);
	initSMotor(arm, 20, armM);
	initSMotor(serv, 10, servM);

	while (true)
	{

		updateSMotor(left, vexRT[Ch2]);
		updateSMotor(right, vexRT[Ch2]);
		updateSMotor(arm, vexRT[Ch3]);
		updateSMotor(serv, vexRT[Ch4]);

	}

}
